### ISSUE TITLE
Let z-index configurable

### ISSUE THREAD

**Issue by hongquan** [kullna/editor#31]
[x] I would be willing to contribute this feature to the project if given guidance and support.

**Is your feature request related to a problem? Please describe.** 

I'm trying to integrate Kullna Editor to an web page using VueJS + TailwindCSS. I notice that Kullna creates a copy of editing text in a `div` element with `z-index=100`.

I wonder if this z-index value is configurable, I want to lower it. It is becase my page also have a modal popup, with z-index 40 lower than Kullna editor.

**Additional context** 

![image](https://github.com/kullna/editor/assets/314607/13d755b9-4062-4da1-9e45-c34acaa88ea1)

**Comment by StevenEWright** [comment]
Agreed - this was a hack 😄...

I've fixed the issue. I'm just cleaning up some of the documentation now, and I'll push a PR.

**Comment by StevenEWright** [comment]
Hey @hongquan! Thanks for the report! I've removed the use of zindex altogether since it was a hack to begin with. Things should "just work" now for you. Let me know if not. 

Also, one note; previously the editor added `position: relative` to itself... it won't anymore. So if you were relying on that before, you will have to add `position: relative` to your css class now. Sorry about that.

**Comment by hongquan** [comment]
Thank you. It works well now. This is my code of integration Kullna Editor with VueJS + TailwindCSS: https://github.com/hongquan/QuanWeb/blob/8e56d26bffcd1c10aeac6dbeb482871c8306e178/admin/src/views/BlogPostEdit.vue#L287
